---
short_host_name: "{{ host_name | regex_replace('\\..*$', '') }}"
domain_name: "{{ host_name | regex_replace('^[^.]*\\.', '') }}"
dev_btrfs: /dev/sdb
guest_dns: 10.0.2.3
guests:
  - { name: guest01, ip: 192.168.1.11/24 }
  - { name: guest02, ip: 192.168.1.12/24 }
  - { name: guest03, ip: 192.168.1.13/24 }
guest_gateway: 192.168.1.1
